#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using Object = UnityEngine.Object;

namespace Anaglyph
{
	// TextCore and TextMeshPro asset inspectors are hand-drawn IMGUI without [CanEditMultipleObjects],
	// so selecting a folder of font assets leaves you editing them one at a time. A multi-object
	// SerializedObject *does* support batch editing, so this window rebuilds the useful parts of those
	// inspectors on top of one, and adds the list/material operations a plain property field can't express.
	//
	// Everything is driven by SerializedProperty paths rather than concrete types. That way the same
	// window handles UnityEngine.TextCore.Text.FontAsset, TMPro.TMP_FontAsset, sprite assets and style
	// sheets alike — and this assembly needs no reference to TextMeshPro.
	public class TextCoreBatchEditor : EditorWindow
	{
		// Arrays past this length are shown as a label instead of a field. Glyph and character tables
		// run to thousands of entries; drawing them across dozens of assets locks up the editor.
		private const int MaxArrayElements = 64;

		// Serialized data that is huge, regenerated by Unity, or purely a runtime lookup cache.
		// Revealed by the "Internal tables" toggle, still subject to MaxArrayElements.
		private static readonly HashSet<string> internalPaths = new HashSet<string>
		{
			"m_Script", "m_Name", "m_EditorClassIdentifier", "m_InstanceID", "m_Version",
			"hashCode", "materialHashCode", "m_MaterialHashCode", "m_SourceFontFileGUID",
			"m_GlyphTable", "m_CharacterTable", "m_UsedGlyphRects", "m_FreeGlyphRects",
			"m_FontFeatureTable", "m_KerningTable", "m_glyphInfoList", "m_fontInfo",
			"m_AtlasTextures", "m_AtlasTextureIndex", "atlas",
			"m_SpriteCharacterTable", "m_SpriteGlyphTable", "spriteInfoList",
		};

		private readonly struct Section
		{
			public readonly string title;
			public readonly bool copyable;
			public readonly string[] paths;

			public Section(string title, bool copyable, params string[] paths)
			{
				this.title = title;
				this.copyable = copyable;
				this.paths = paths;
			}
		}

		// Both naming conventions are listed side by side: TextCore uses m_-prefixed fields, the older
		// TMP types use bare ones. Only the paths that actually exist on the selected type get drawn.
		private static readonly Section[] sections =
		{
			// Not copyable: every one of these points at that asset's own source font or atlas
			// sub-asset, so copying them from a template would repoint all of them at one atlas.
			new Section("Source", false,
				"m_SourceFontFile", "m_SourceFontFile_EditorRef", "m_SourceFontFilePath",
				"m_Material", "material", "spriteSheet", "m_SpriteSheet"),

			new Section("Face Info", true,
				"m_FaceInfo"),

			new Section("Atlas", true,
				"m_AtlasPopulationMode", "m_AtlasWidth", "m_AtlasHeight", "m_AtlasPadding",
				"m_AtlasRenderMode", "m_IsMultiAtlasTexturesEnabled", "m_ClearDynamicDataOnBuild",
				"m_GetFontFeatures", "m_ShouldReimportFontFeatures", "InternalDynamicOS", "IsEditorFont"),

			new Section("Style & Metrics", true,
				"m_RegularStyleWeight", "m_RegularStyleSpacing", "m_BoldStyleWeight", "m_BoldStyleSpacing",
				"m_ItalicStyleSlant", "m_TabMultiple",
				"normalStyle", "normalSpacingOffset", "boldStyle", "boldSpacing", "italicStyle", "tabSize"),

			new Section("Weights & Fallbacks", true,
				"m_FontWeightTable", "fontWeights",
				"m_FallbackFontAssetTable", "fallbackFontAssets",
				"m_FallbackSpriteAssets", "fallbackSpriteAssets"),

			new Section("Generation Settings", true,
				"m_fontAssetCreationEditorSettings", "m_CreationSettings"),
		};

		private enum ListOp { Add, Remove, Replace, Clear }

		private class Group
		{
			public Type type;
			public readonly List<Object> objects = new List<Object>();
			public SerializedObject serialized;
			public List<string> paths = new List<string>();
			// Kept paired so an atlas material can be resolved back to the settings of its own font asset.
			public readonly List<(Object asset, Material material)> materials = new List<(Object, Material)>();
		}

		private readonly List<Object> targets = new List<Object>();
		private readonly List<Group> groups = new List<Group>();

		// Keyed by type name so the state survives a rebuild of the groups.
		private readonly Dictionary<string, bool> foldouts = new Dictionary<string, bool>();
		private readonly Dictionary<string, Object> templates = new Dictionary<string, Object>();
		private readonly Dictionary<string, int> listIndices = new Dictionary<string, int>();
		private readonly Dictionary<string, Object> listValues = new Dictionary<string, Object>();

		private bool followSelection;
		private bool showInternal;
		private bool showTargets;
		private bool rebuildQueued;
		private Vector2 scroll;

		private static GUIStyle sectionStyle;
		private static GUIStyle SectionStyle => sectionStyle ??=
			new GUIStyle(EditorStyles.foldout) { fontStyle = FontStyle.Bold };

		[MenuItem("Window/Lasertag/TextCore Batch Editor")]
		public static void ShowWindow()
		{
			GetWindow<TextCoreBatchEditor>("TextCore Batch");
		}

		[MenuItem("Assets/Batch Edit TextCore Assets", false, 30)]
		private static void EditSelection()
		{
			TextCoreBatchEditor window = GetWindow<TextCoreBatchEditor>("TextCore Batch");
			window.AddObjects(Selection.objects);
		}

		[MenuItem("Assets/Batch Edit TextCore Assets", true)]
		private static bool ValidateEditSelection()
		{
			// Deliberately cheap — this runs every time the context menu opens, so it checks for
			// something plausible rather than scanning whole folders for real targets.
			foreach (Object o in Selection.objects)
			{
				if (IsTextCoreAsset(o))
					return true;

				string path = AssetDatabase.GetAssetPath(o);
				if (!string.IsNullOrEmpty(path) && AssetDatabase.IsValidFolder(path))
					return true;
			}

			return false;
		}

		private void OnDisable()
		{
			DisposeGroups();
		}

		private void OnSelectionChange()
		{
			if (!followSelection)
				return;

			targets.Clear();
			AddObjects(Selection.objects);
		}

		// ------------------------------------------------------------------ targets

		private static bool IsTextCoreAsset(Object o)
		{
			if (o == null || !(o is ScriptableObject))
				return false;

			for (Type type = o.GetType(); type != null; type = type.BaseType)
				if (type.Namespace == "UnityEngine.TextCore.Text" || type.Namespace == "TMPro")
					return true;

			return false;
		}

		private void AddObjects(IEnumerable<Object> objects)
		{
			foreach (Object o in objects)
				Collect(o);

			RequestRebuild();
		}

		// Rebuilding replaces the group list and its SerializedObjects. Doing that partway through
		// OnGUI would both invalidate the loop walking the groups and leave IMGUI's layout pass
		// describing a different window than its repaint pass, so it is always deferred a frame.
		private void RequestRebuild()
		{
			rebuildQueued = true;
			Repaint();
		}

		private void Collect(Object o)
		{
			if (o == null)
				return;

			string path = AssetDatabase.GetAssetPath(o);

			if (!string.IsNullOrEmpty(path) && AssetDatabase.IsValidFolder(path))
			{
				foreach (string guid in AssetDatabase.FindAssets(string.Empty, new[] { path }))
				{
					string assetPath = AssetDatabase.GUIDToAssetPath(guid);

					// Only .asset files can hold these types; skipping the rest avoids importing
					// every texture and mesh in the folder just to test its type.
					if (!assetPath.EndsWith(".asset", StringComparison.OrdinalIgnoreCase))
						continue;

					foreach (Object sub in AssetDatabase.LoadAllAssetsAtPath(assetPath))
						Add(sub);
				}

				return;
			}

			Add(o);
		}

		private void Add(Object o)
		{
			if (IsTextCoreAsset(o) && !targets.Contains(o))
				targets.Add(o);
		}

		private void DisposeGroups()
		{
			foreach (Group group in groups)
				group.serialized?.Dispose();

			groups.Clear();
		}

		private void Rebuild()
		{
			DisposeGroups();
			targets.RemoveAll(t => t == null);

			// A SerializedObject can only span objects of one type, so batch per concrete type.
			foreach (Object target in targets)
			{
				Group group = groups.FirstOrDefault(g => g.type == target.GetType());

				if (group == null)
					groups.Add(group = new Group { type = target.GetType() });

				group.objects.Add(target);
			}

			foreach (Group group in groups)
			{
				group.serialized = new SerializedObject(group.objects.ToArray());
				group.paths = TopLevelPaths(group.serialized);
				CollectMaterials(group);
			}
		}

		private static List<string> TopLevelPaths(SerializedObject serialized)
		{
			List<string> paths = new List<string>();

			SerializedProperty iterator = serialized.GetIterator();
			bool enterChildren = true;

			while (iterator.NextVisible(enterChildren))
			{
				enterChildren = false; // nested values are drawn by their parent's foldout
				paths.Add(iterator.propertyPath);
			}

			return paths;
		}

		private static void CollectMaterials(Group group)
		{
			group.materials.Clear();

			// The shared SerializedObject only reports the first object's value for an object
			// reference, so each asset needs its own to find its atlas material.
			foreach (Object asset in group.objects)
			{
				using SerializedObject serialized = new SerializedObject(asset);

				foreach (string path in new[] { "m_Material", "material" })
				{
					SerializedProperty property = serialized.FindProperty(path);

					if (property == null || property.propertyType != SerializedPropertyType.ObjectReference)
						continue;

					if (property.objectReferenceValue is Material material &&
					    !group.materials.Any(pair => pair.material == material))
						group.materials.Add((asset, material));
				}
			}
		}

		// ------------------------------------------------------------------ gui

		private void OnGUI()
		{
			if (rebuildQueued)
			{
				rebuildQueued = false;
				Rebuild();
			}

			DrawToolbar();

			scroll = EditorGUILayout.BeginScrollView(scroll);

			DrawTargets();

			if (groups.Count == 0)
				EditorGUILayout.HelpBox(
					"Select font assets, sprite assets or style sheets and press Add Selection, " +
					"or drop assets and folders onto the box above.", MessageType.Info);

			foreach (Group group in groups)
				DrawGroup(group);

			EditorGUILayout.EndScrollView();

			DrawFooter();
		}

		private void DrawToolbar()
		{
			EditorGUILayout.BeginHorizontal(EditorStyles.toolbar);

			if (GUILayout.Button("Add Selection", EditorStyles.toolbarButton, GUILayout.Width(100)))
				AddObjects(Selection.objects);

			using (new EditorGUI.DisabledScope(targets.Count == 0))
				if (GUILayout.Button("Clear", EditorStyles.toolbarButton, GUILayout.Width(50)))
				{
					targets.Clear();
					RequestRebuild();
				}

			GUILayout.FlexibleSpace();

			EditorGUI.BeginChangeCheck();
			followSelection = GUILayout.Toggle(followSelection, "Follow Selection",
				EditorStyles.toolbarButton, GUILayout.Width(110));
			if (EditorGUI.EndChangeCheck() && followSelection)
			{
				targets.Clear();
				AddObjects(Selection.objects);
			}

			showInternal = GUILayout.Toggle(showInternal, "Internal Tables",
				EditorStyles.toolbarButton, GUILayout.Width(105));

			EditorGUILayout.EndHorizontal();
		}

		private void DrawTargets()
		{
			Rect drop = GUILayoutUtility.GetRect(0, 34, GUILayout.ExpandWidth(true));
			GUI.Box(drop, "Drop font assets, sprite assets or folders here", EditorStyles.helpBox);
			HandleDrop(drop);

			if (targets.Count == 0)
				return;

			showTargets = EditorGUILayout.Foldout(showTargets, $"Targets ({targets.Count})", true);

			if (!showTargets)
				return;

			EditorGUI.indentLevel++;

			int remove = -1;

			for (int i = 0; i < targets.Count; i++)
			{
				EditorGUILayout.BeginHorizontal();
				EditorGUILayout.ObjectField(targets[i], targets[i].GetType(), false);

				if (GUILayout.Button("-", EditorStyles.miniButton, GUILayout.Width(22)))
					remove = i;

				EditorGUILayout.EndHorizontal();
			}

			EditorGUI.indentLevel--;

			if (remove >= 0)
			{
				targets.RemoveAt(remove);
				RequestRebuild();
			}
		}

		private void HandleDrop(Rect rect)
		{
			Event e = Event.current;

			if (!rect.Contains(e.mousePosition))
				return;

			if (e.type == EventType.DragUpdated)
			{
				DragAndDrop.visualMode = DragAndDropVisualMode.Copy;
				e.Use();
			}
			else if (e.type == EventType.DragPerform)
			{
				DragAndDrop.AcceptDrag();
				AddObjects(DragAndDrop.objectReferences);
				e.Use();
			}
		}

		private void DrawGroup(Group group)
		{
			EditorGUILayout.Space();
			EditorGUILayout.LabelField($"{group.type.Name}  ({group.objects.Count})", EditorStyles.boldLabel);

			DrawTemplateField(group);

			group.serialized.Update();

			foreach (Section section in sections)
			{
				List<string> present = section.paths.Where(p => group.paths.Contains(p)).ToList();

				if (present.Count > 0)
					DrawSection(group, section.title, present, section.copyable);
			}

			List<string> other = group.paths.Where(IsUncategorized).ToList();

			if (other.Count > 0)
				DrawSection(group, "Other", other, true);

			group.serialized.ApplyModifiedProperties();

			DrawListOperations(group);
			DrawMaterials(group);
		}

		private bool IsUncategorized(string path)
		{
			if (internalPaths.Contains(path))
				return showInternal;

			return !sections.Any(s => Array.IndexOf(s.paths, path) >= 0);
		}

		private void DrawTemplateField(Group group)
		{
			templates.TryGetValue(group.type.FullName, out Object template);

			EditorGUILayout.BeginHorizontal();
			template = EditorGUILayout.ObjectField("Copy Template", template, group.type, false);

			using (new EditorGUI.DisabledScope(template == null))
				if (GUILayout.Button("Copy All", EditorStyles.miniButton, GUILayout.Width(70)))
					CopyFromTemplate(group, sections.Where(s => s.copyable).SelectMany(s => s.paths).ToList());

			EditorGUILayout.EndHorizontal();

			templates[group.type.FullName] = template;
		}

		private void DrawSection(Group group, string title, List<string> paths, bool copyable)
		{
			string key = group.type.FullName + "/" + title;
			foldouts.TryGetValue(key, out bool open);
			templates.TryGetValue(group.type.FullName, out Object template);

			EditorGUILayout.BeginHorizontal();
			foldouts[key] = EditorGUILayout.Foldout(open, title, true, SectionStyle);

			using (new EditorGUI.DisabledScope(!copyable || template == null))
				if (GUILayout.Button("Copy", EditorStyles.miniButton, GUILayout.Width(50)))
					CopyFromTemplate(group, paths);

			EditorGUILayout.EndHorizontal();

			if (!foldouts[key])
				return;

			EditorGUI.indentLevel++;

			if (title == "Source")
				EditorGUILayout.HelpBox(
					"These point at each asset's own source font and atlas sub-asset. " +
					"Assigning a value here writes it to every selected asset.", MessageType.Warning);

			if (title == "Atlas")
				EditorGUILayout.HelpBox(
					"Changing size, padding or render mode does not regenerate the atlas textures. " +
					"Regenerate each font from its own inspector, then use Sync To Atlas Settings below.",
					MessageType.Info);

			foreach (string path in paths)
			{
				SerializedProperty property = group.serialized.FindProperty(path);

				if (property == null)
					continue;

				if (property.isArray && property.propertyType != SerializedPropertyType.String &&
				    property.arraySize > MaxArrayElements)
				{
					EditorGUILayout.LabelField(property.displayName,
						$"{property.arraySize} elements — too large to batch edit");
					continue;
				}

				EditorGUILayout.PropertyField(property, true);
			}

			EditorGUI.indentLevel--;
		}

		private void CopyFromTemplate(Group group, List<string> paths)
		{
			if (!templates.TryGetValue(group.type.FullName, out Object template) || template == null)
				return;

			using SerializedObject source = new SerializedObject(template);

			foreach (Object asset in group.objects)
			{
				if (asset == template)
					continue;

				using SerializedObject destination = new SerializedObject(asset);

				foreach (string path in paths)
				{
					SerializedProperty property = source.FindProperty(path);

					if (property != null)
						destination.CopyFromSerializedProperty(property);
				}

				destination.ApplyModifiedProperties();
			}

			// Array lengths may have changed, which the shared SerializedObject caches.
			RequestRebuild();
		}

		// ------------------------------------------------------------------ list operations

		// Multi-object property fields cannot edit arrays whose lengths differ between assets, which
		// is exactly the case for fallback tables. These operations run per asset instead, so a single
		// fallback can be added to or removed from every selected asset regardless of its current list.
		private void DrawListOperations(Group group)
		{
			List<string> lists = group.paths.Where(path =>
			{
				// m_AtlasTextures and friends are object arrays too, but rewriting them by hand
				// desynchronises the glyph table from its atlas pages.
				if (internalPaths.Contains(path) && !showInternal)
					return false;

				SerializedProperty property = group.serialized.FindProperty(path);
				return property != null && property.isArray && property.arrayElementType.StartsWith("PPtr<");
			}).ToList();

			if (lists.Count == 0)
				return;

			string key = group.type.FullName + "/@lists";
			foldouts.TryGetValue(key, out bool open);
			foldouts[key] = EditorGUILayout.Foldout(open, "List Operations", true, SectionStyle);

			if (!foldouts[key])
				return;

			EditorGUI.indentLevel++;

			listIndices.TryGetValue(group.type.FullName, out int index);
			index = EditorGUILayout.Popup("List", Mathf.Clamp(index, 0, lists.Count - 1),
				lists.Select(ObjectNames.NicifyVariableName).ToArray());
			listIndices[group.type.FullName] = index;

			string listPath = lists[index];
			Type elementType = ElementType(group.serialized.FindProperty(listPath));

			listValues.TryGetValue(group.type.FullName, out Object value);
			value = EditorGUILayout.ObjectField("Value", value, elementType, false);
			listValues[group.type.FullName] = value;

			EditorGUILayout.BeginHorizontal();
			EditorGUILayout.PrefixLabel(" ");

			using (new EditorGUI.DisabledScope(value == null))
			{
				if (GUILayout.Button("Add"))
					ApplyListOp(group, listPath, value, ListOp.Add);

				if (GUILayout.Button("Remove"))
					ApplyListOp(group, listPath, value, ListOp.Remove);

				if (GUILayout.Button("Replace All"))
					ApplyListOp(group, listPath, value, ListOp.Replace);
			}

			if (GUILayout.Button("Clear"))
				ApplyListOp(group, listPath, null, ListOp.Clear);

			EditorGUILayout.EndHorizontal();
			EditorGUI.indentLevel--;
		}

		// arrayElementType reads "PPtr<$TMP_FontAsset>"; the name inside is enough to type the field.
		private static Type ElementType(SerializedProperty array)
		{
			string element = array.arrayElementType;
			int start = element.IndexOf('$');
			int end = element.LastIndexOf('>');

			if (start < 0 || end <= start)
				return typeof(Object);

			string name = element.Substring(start + 1, end - start - 1);

			return TypeCache.GetTypesDerivedFrom<Object>().FirstOrDefault(t => t.Name == name) ?? typeof(Object);
		}

		private void ApplyListOp(Group group, string path, Object value, ListOp op)
		{
			foreach (Object asset in group.objects)
			{
				using SerializedObject serialized = new SerializedObject(asset);
				SerializedProperty list = serialized.FindProperty(path);

				if (list == null || !list.isArray)
					continue;

				switch (op)
				{
					case ListOp.Clear:
						list.ClearArray();
						break;

					case ListOp.Replace:
						list.ClearArray();
						AppendUnique(list, asset, value);
						break;

					case ListOp.Remove:
						for (int i = list.arraySize - 1; i >= 0; i--)
							if (list.GetArrayElementAtIndex(i).objectReferenceValue == value)
								RemoveAt(list, i);
						break;

					case ListOp.Add:
						AppendUnique(list, asset, value);
						break;
				}

				serialized.ApplyModifiedProperties();
			}

			RequestRebuild();
		}

		private static void AppendUnique(SerializedProperty list, Object owner, Object value)
		{
			// An asset falling back to itself is an infinite loop at lookup time.
			if (value == null || value == owner)
				return;

			for (int i = 0; i < list.arraySize; i++)
				if (list.GetArrayElementAtIndex(i).objectReferenceValue == value)
					return;

			int index = list.arraySize;
			list.InsertArrayElementAtIndex(index);
			list.GetArrayElementAtIndex(index).objectReferenceValue = value;
		}

		// For arrays of object references, DeleteArrayElementAtIndex historically nulls the entry
		// instead of removing it, and a second call is needed to close the gap.
		private static void RemoveAt(SerializedProperty list, int index)
		{
			int size = list.arraySize;
			list.DeleteArrayElementAtIndex(index);

			if (list.arraySize == size && index < list.arraySize &&
			    list.GetArrayElementAtIndex(index).objectReferenceValue == null)
				list.DeleteArrayElementAtIndex(index);
		}

		// ------------------------------------------------------------------ materials

		// MaterialEditor refuses to multi-edit materials that use different shaders, which font atlas
		// materials routinely do (Distance Field vs Mobile vs SSD). This draws the union of their
		// shader properties and writes each change only to the materials that declare it.
		private void DrawMaterials(Group group)
		{
			if (group.materials.Count == 0)
				return;

			string key = group.type.FullName + "/@materials";
			foldouts.TryGetValue(key, out bool open);

			EditorGUILayout.BeginHorizontal();
			foldouts[key] = EditorGUILayout.Foldout(open,
				$"Atlas Materials ({group.materials.Count})", true, SectionStyle);

			if (GUILayout.Button(new GUIContent("Sync To Atlas Settings",
					"Writes each asset's atlas width, height and padding into its own material."),
				EditorStyles.miniButton, GUILayout.Width(150)))
				SyncMaterialsToAtlas(group);

			EditorGUILayout.EndHorizontal();

			if (!foldouts[key])
				return;

			List<Material> materials = group.materials.Select(pair => pair.material).ToList();

			EditorGUI.indentLevel++;

			foreach ((string name, string label, ShaderPropertyType type, Vector2 range) property in
			         ShaderProperties(materials))
				DrawMaterialProperty(materials, property);

			EditorGUI.indentLevel--;
		}

		private static IEnumerable<(string name, string label, ShaderPropertyType type, Vector2 range)>
			ShaderProperties(List<Material> materials)
		{
			HashSet<string> seen = new HashSet<string>();

			foreach (Material material in materials)
			{
				Shader shader = material != null ? material.shader : null;

				if (shader == null)
					continue;

				int count = shader.GetPropertyCount();

				for (int i = 0; i < count; i++)
				{
					if ((shader.GetPropertyFlags(i) & ShaderPropertyFlags.HideInInspector) != 0)
						continue;

					string name = shader.GetPropertyName(i);

					if (!seen.Add(name))
						continue;

					ShaderPropertyType type = shader.GetPropertyType(i);

					yield return (name, shader.GetPropertyDescription(i), type,
						type == ShaderPropertyType.Range ? shader.GetPropertyRangeLimits(i) : Vector2.zero);
				}
			}
		}

		private static void DrawMaterialProperty(List<Material> materials,
			(string name, string label, ShaderPropertyType type, Vector2 range) property)
		{
			List<Material> owners = materials
				.Where(m => m != null && m.HasProperty(property.name)).ToList();

			if (owners.Count == 0)
				return;

			GUIContent label = new GUIContent(
				string.IsNullOrEmpty(property.label) ? property.name : property.label, property.name);

			switch (property.type)
			{
				case ShaderPropertyType.Color:
				{
					Color value = owners[0].GetColor(property.name);
					EditorGUI.showMixedValue = owners.Any(m => m.GetColor(property.name) != value);

					EditorGUI.BeginChangeCheck();
					Color next = EditorGUILayout.ColorField(label, value);
					if (EditorGUI.EndChangeCheck())
						Write(owners, m => m.SetColor(property.name, next));

					break;
				}

				case ShaderPropertyType.Vector:
				{
					Vector4 value = owners[0].GetVector(property.name);
					EditorGUI.showMixedValue = owners.Any(m => m.GetVector(property.name) != value);

					EditorGUI.BeginChangeCheck();
					Vector4 next = EditorGUILayout.Vector4Field(label, value);
					if (EditorGUI.EndChangeCheck())
						Write(owners, m => m.SetVector(property.name, next));

					break;
				}

				case ShaderPropertyType.Range:
				{
					float value = owners[0].GetFloat(property.name);
					EditorGUI.showMixedValue = owners.Any(m => !Mathf.Approximately(m.GetFloat(property.name), value));

					EditorGUI.BeginChangeCheck();
					float next = EditorGUILayout.Slider(label, value, property.range.x, property.range.y);
					if (EditorGUI.EndChangeCheck())
						Write(owners, m => m.SetFloat(property.name, next));

					break;
				}

				case ShaderPropertyType.Float:
				{
					float value = owners[0].GetFloat(property.name);
					EditorGUI.showMixedValue = owners.Any(m => !Mathf.Approximately(m.GetFloat(property.name), value));

					EditorGUI.BeginChangeCheck();
					float next = EditorGUILayout.FloatField(label, value);
					if (EditorGUI.EndChangeCheck())
						Write(owners, m => m.SetFloat(property.name, next));

					break;
				}

				case ShaderPropertyType.Int:
				{
					int value = owners[0].GetInteger(property.name);
					EditorGUI.showMixedValue = owners.Any(m => m.GetInteger(property.name) != value);

					EditorGUI.BeginChangeCheck();
					int next = EditorGUILayout.IntField(label, value);
					if (EditorGUI.EndChangeCheck())
						Write(owners, m => m.SetInteger(property.name, next));

					break;
				}

				case ShaderPropertyType.Texture:
				{
					Texture value = owners[0].GetTexture(property.name);
					EditorGUI.showMixedValue = owners.Any(m => m.GetTexture(property.name) != value);

					EditorGUI.BeginChangeCheck();
					Texture next = (Texture)EditorGUILayout.ObjectField(label, value, typeof(Texture), false);
					if (EditorGUI.EndChangeCheck())
						Write(owners, m => m.SetTexture(property.name, next));

					break;
				}
			}

			EditorGUI.showMixedValue = false;
		}

		private static void Write(List<Material> materials, Action<Material> write)
		{
			Undo.RecordObjects(materials.ToArray(), "Batch Edit Atlas Materials");

			foreach (Material material in materials)
			{
				write(material);
				EditorUtility.SetDirty(material);
			}
		}

		// The atlas dimensions and the SDF gradient scale are baked into material floats, and are only
		// refreshed when a font asset regenerates its atlas from its own inspector. A batch change to
		// padding or atlas size therefore leaves every material describing the old atlas.
		private void SyncMaterialsToAtlas(Group group)
		{
			Undo.RecordObjects(group.materials.Select(pair => pair.material).ToArray(), "Sync Atlas Materials");

			foreach ((Object asset, Material material) in group.materials)
			{
				if (material == null)
					continue;

				using SerializedObject serialized = new SerializedObject(asset);

				SetIfPresent(material, "_TextureWidth", serialized.FindProperty("m_AtlasWidth"));
				SetIfPresent(material, "_TextureHeight", serialized.FindProperty("m_AtlasHeight"));

				SerializedProperty padding = serialized.FindProperty("m_AtlasPadding");

				// TMP's shaders expect the gradient scale to be the atlas padding plus one.
				if (padding != null && material.HasProperty("_GradientScale"))
					material.SetFloat("_GradientScale", padding.intValue + 1);

				EditorUtility.SetDirty(material);
			}
		}

		private static void SetIfPresent(Material material, string name, SerializedProperty value)
		{
			if (value != null && material.HasProperty(name))
				material.SetFloat(name, value.intValue);
		}

		// ------------------------------------------------------------------ footer

		private void DrawFooter()
		{
			EditorGUILayout.BeginHorizontal(EditorStyles.toolbar);

			int materialCount = groups.Sum(g => g.materials.Count);
			GUILayout.Label($"{targets.Count} assets · {groups.Count} types · {materialCount} materials",
				EditorStyles.miniLabel);

			GUILayout.FlexibleSpace();

			if (GUILayout.Button("Save Assets", EditorStyles.toolbarButton, GUILayout.Width(90)))
				AssetDatabase.SaveAssets();

			EditorGUILayout.EndHorizontal();
		}
	}
}
#endif
